/**
 * Repair guides: the public, indexable pages under /repairs/.
 *
 * scripts/pages.js turns this into HTML at build time, and eval/local-check.js
 * validates it. Each guide links into the app with the job typed in, using the
 * same wording as the matching job in eval/jobs.json, so what a guide promises
 * is what the tool has been tested on.
 *
 * Ground rules for anything added here:
 *   - Low-risk jobs only. Nothing that has someone working on gas, mains
 *     electrical, structure, refrigerant or brakes. Those belong in callPro.
 *   - Checks go cheapest and most likely first, the same order the app uses.
 *   - No prices and no aisle numbers. Both vary by store, and the app gives
 *     store-specific estimates; a static page would state them as fact.
 *   - No "exact", "guaranteed" or similar. The app's own disclosure says
 *     aisles and prices are estimates.
 */

const TRADES = [
  {
    key: 'plumbing',
    name: 'Plumbing',
    title: 'Plumbing Repair Parts Lists',
    description: 'Describe a plumbing problem and get a one-trip parts list for Home Depot or Lowe\'s: traps, washers, supply lines and toilet parts. Free guides for common fixes.',
    intro: 'Leaks, clogs, running toilets and dripping faucets make up most household plumbing trouble, and the hard part of the store run is knowing which size and type of part to grab. Describe the problem or add a photo and Ask Danny builds the list for your store.',
    covers: [
      'Drain parts: P-traps, slip nuts and washers, extension tubes, drain snakes',
      'Toilet parts: flappers, fill valves, wax rings',
      'Supply lines, shutoff valves, push-to-connect and PVC fittings',
      'Faucet cartridges, washers, O-rings and aerators',
      'Garbage disposal parts and sump pump parts',
    ],
    stores: 'Home Depot and Lowe\'s',
    callPro: [
      'Anything involving a gas line or a gas water heater. If you smell gas, leave the building and call your gas utility from outside.',
      'Leaks inside a wall or ceiling, or a burst pipe',
      'Sewage backing up, or several drains in the house slow at once',
      'Work that needs a permit where you live',
    ],
  },
  {
    key: 'hvac',
    name: 'HVAC',
    title: 'Basic HVAC Repair Parts Lists',
    description: 'Parts lists for basic heating and cooling fixes: air filters, condensate drains, thermostats and vents, with aisle guidance for Home Depot and Lowe\'s.',
    intro: 'A lot of heating and cooling problems come down to airflow and drainage: a clogged filter, a blocked condensate line, a closed vent. Those are homeowner jobs. Ask Danny lists the parts for them and tells you when a problem is not one.',
    covers: [
      'Air filters by size and MERV rating',
      'Condensate drain line parts and cleaning supplies',
      'Programmable and smart thermostats, thermostat wire',
      'Vent registers, return grilles, foil tape and duct sealant',
    ],
    stores: 'Home Depot and Lowe\'s',
    callPro: [
      'Any smell of gas. Leave the building and call your gas utility from outside.',
      'Refrigerant: a coil that keeps freezing with good airflow, or oily residue at the lines',
      'Capacitors and wiring inside the outdoor unit, which can hold a dangerous charge with the power off',
      'Furnace ignition problems, or a furnace that starts and shuts off',
    ],
  },
  {
    key: 'carpentry',
    name: 'Carpentry',
    title: 'Carpentry and Drywall Repair Parts Lists',
    description: 'Parts lists for drywall patches, sticking doors, loose hardware and trim repairs, with the fasteners and tools you need in one trip to Home Depot or Lowe\'s.',
    intro: 'Small carpentry repairs go wrong at the store: the wrong screw length, the wrong drywall thickness, a latch that does not match the door. Describe the job and Ask Danny lists the pieces that fit together.',
    covers: [
      'Drywall, patches, joint compound, tape and corner bead',
      'Door hinges, strike plates, latches, shims and sweeps',
      'Cabinet hinges and drawer slides',
      'Screws, nails, construction adhesive and trim',
    ],
    stores: 'Home Depot and Lowe\'s',
    callPro: [
      'Removing or cutting into any wall that might be load-bearing',
      'Rotted framing, sagging floors or ceilings, or new cracks that keep growing',
      'Stair railings and anything else that has to hold a person\'s weight',
      'Damage caused by a water leak, until the leak is found and fixed',
    ],
  },
  {
    key: 'auto',
    name: 'Auto',
    title: 'Car Repair Parts Lists for AutoZone',
    description: 'Parts lists for simple car fixes: wiper blades, headlight bulbs, batteries, fluids and filters, matched to your vehicle with aisle guidance for AutoZone.',
    intro: 'Most quick car fixes start with the same question at the parts counter: which one fits my car? Tell Ask Danny the year, make, model and what is wrong, and it lists the parts to ask for.',
    covers: [
      'Wiper blades, headlight and tail light bulbs, fuses',
      'Batteries, terminal cleaners and protectors',
      'Motor oil, oil and air filters, coolant, washer fluid',
      'Tire pressure gauges, plug kits and valve stems',
    ],
    stores: 'AutoZone',
    callPro: [
      'Brakes and steering, unless you have done that work before',
      'A flashing check engine light or an engine that shakes badly. Stop driving and have it checked.',
      'A temperature gauge in the red. Pull over and let the engine cool before opening anything.',
      'Airbags, and high-voltage parts on hybrids, EVs and HID headlights',
    ],
  },
  {
    key: 'appliance',
    name: 'Appliance',
    title: 'Appliance Repair Parts Lists',
    description: 'Parts lists for washer, dryer, fridge and dishwasher problems: hoses, filters, gaskets, vent kits and pumps, with aisle guidance for Home Depot and Lowe\'s.',
    intro: 'Many appliance problems are a clogged filter, a kinked hose or a worn gasket rather than a dead machine. Ask Danny helps you rule those out and lists the parts, with the model number details to check before you buy.',
    covers: [
      'Washer hoses, drain pumps and leveling feet',
      'Dryer vent kits, lint brushes and thermal fuses',
      'Refrigerator water filters, door gaskets and water lines',
      'Dishwasher supply lines, drain hoses and install kits',
    ],
    stores: 'Home Depot and Lowe\'s',
    callPro: [
      'Gas dryers and gas ranges that will not heat, or any smell of gas. If you smell gas, leave and call your gas utility from outside.',
      'Refrigerators that are not cooling at all, which can mean a sealed-system problem',
      'Control boards and internal wiring',
      'Anything still under warranty, where a repair by you could void it',
    ],
  },
];

const JOBS = [
  {
    slug: 'toilet-keeps-running',
    trade: 'plumbing',
    h1: 'Toilet keeps running: what to check and what to buy',
    title: 'Toilet Keeps Running? Parts and What to Check First',
    description: 'A running toilet is almost always the flapper, the chain or the fill valve. Check them in this order before you buy parts, and see what to pick up at the store.',
    lede: 'A running toilet is almost always one of three parts inside the tank, and the cheapest one is the most common culprit. Take the tank lid off and check in this order.',
    before: 'To replace a part, turn off the shutoff valve behind the toilet and flush to empty the tank first.',
    checks: [
      ['The flapper', 'Push down on the rubber flapper at the bottom of the tank. If the running stops, the flapper is not sealing because it is warped, stiff or coated in mineral buildup. This is the most common cause and the cheapest fix.'],
      ['The flapper chain', 'A chain that is too short holds the flapper open, and one that is too long can get caught under it. Leave about half an inch of slack.'],
      ['The water level', 'If water is spilling into the overflow tube, the fill level is set too high. Lower the float until the water stops about an inch below the top of the tube.'],
      ['The fill valve', 'If the water still will not shut off, or the valve hisses and refills on its own, replace the fill valve.'],
      ['The flush valve seat', 'If a new flapper still leaks, the seat it rests on may be pitted or cracked. Replacing the whole flush valve means taking the tank off the bowl.'],
    ],
    parts: [
      ['Toilet flapper', 'Match the drain opening, usually 2 or 3 inches. Bring the old one to compare.'],
      ['Toilet fill valve', 'Adjustable universal models fit most toilets.'],
      ['Flapper chain', 'Usually included with a new flapper.'],
      ['Flush valve kit', 'Only if the valve seat itself is damaged.'],
    ],
    tools: ['Sponge and towel', 'Adjustable wrench', 'Small bucket'],
    callPro: [
      'The tank or bowl is cracked',
      'The shutoff valve will not turn, or leaks when you turn it',
      'Water is leaking onto the floor around the base',
    ],
    appJob: 'My toilet keeps running',
  },
  {
    slug: 'leak-under-kitchen-sink',
    trade: 'plumbing',
    h1: 'Water leaking under the kitchen sink: find it, then fix it',
    title: 'Leak Under the Kitchen Sink: What to Check and Buy',
    description: 'Find where the water under your kitchen sink is coming from, then get the right part: slip washers, a P-trap kit, a basket strainer or new supply lines.',
    lede: 'Dry every pipe and fitting with a paper towel, run the water, and watch for the first drip. Where it starts tells you which part to buy.',
    before: 'Clear out the cabinet and put a towel and a bucket underneath before you start loosening anything.',
    checks: [
      ['Slip nuts on the drain', 'Drips at the plastic joints of the P-trap usually mean a loose slip nut or a worn slip-joint washer. Hand-tighten the nut first, and replace the washer if it still drips.'],
      ['The sink strainer', 'Water running down the outside of the drain pipe from right under the sink comes from the basket strainer seal. Reseal it with plumber\'s putty or replace the strainer.'],
      ['Supply lines and shutoff valves', 'If it drips even when the faucet is off, check the supply lines and the valve stems. Old, kinked or bulging supply lines should be replaced.'],
      ['Dishwasher and disposal connections', 'Check the dishwasher drain hose clamp and the disposal\'s drain connections, if you have them.'],
      ['The faucet', 'Water pooling on top of the cabinet floor from above can come from the faucet base or the sprayer hose.'],
    ],
    parts: [
      ['Slip-joint washers and nuts', 'Kitchen drains are usually 1-1/2 inch.'],
      ['P-trap kit', 'Only if the trap is cracked or corroded. Match the pipe size.'],
      ['Braided faucet supply lines', 'Check the length and both connections. The valve end is usually 3/8 inch compression.'],
      ['Basket strainer and plumber\'s putty', 'If the leak is at the strainer.'],
      ['Hose clamp', 'For a dishwasher drain hose connection.'],
    ],
    tools: ['Flashlight', 'Bucket and towels', 'Channel-lock pliers', 'Adjustable wrench'],
    callPro: [
      'The leak is inside the wall, or behind the shutoff valve',
      'The shutoff valves will not close',
      'The cabinet floor is soft, or you see mold',
    ],
    appJob: 'Water is dripping from the pipe under my kitchen sink',
  },
  {
    slug: 'slow-bathroom-sink-drain',
    trade: 'plumbing',
    h1: 'Slow bathroom sink drain: clear it in this order',
    title: 'Slow Bathroom Sink Drain: What to Check and Buy',
    description: 'Most slow bathroom sinks are hair caught on the pop-up stopper. Clear the clog in this order, and only buy a snake or new drain parts if you need them.',
    lede: 'Bathroom sinks usually clog close to the top, where hair and soap catch on the pop-up stopper. Start there before reaching for chemicals.',
    before: 'Skip chemical drain openers if you might open the trap afterwards. They can splash on you when the pipe comes apart.',
    checks: [
      ['The pop-up stopper', 'Pull the stopper out. Some lift straight up; others come free when you loosen the pivot rod nut on the back of the drain pipe. Clean off the hair and buildup.'],
      ['Just below the stopper', 'Push a plastic drain-cleaning strip or a small hand snake down the drain to pull out what is past the stopper.'],
      ['The P-trap', 'If it is still slow, put a bucket underneath, remove the trap and clean it out.'],
      ['Further down the line', 'If the sink gurgles, or other fixtures are slow too, the clog or a vent problem is past the trap, and that is a job for a plumber.'],
    ],
    parts: [
      ['Plastic drain-cleaning strip', 'A cheap barbed strip that pulls hair out.'],
      ['Hand drain snake', 'A 1/4 inch cable is the right size for sink drains.'],
      ['Slip-joint washers', 'Bathroom sink drains are usually 1-1/4 inch.'],
      ['Pop-up drain assembly', 'Only if the stopper or its linkage is broken or corroded.'],
    ],
    tools: ['Bucket', 'Channel-lock pliers', 'Rubber gloves', 'Flashlight'],
    callPro: [
      'Several drains in the house are slow at once',
      'Water backs up into the tub or another sink',
      'The pipe inside the wall is cracked or leaking',
    ],
    appJob: 'Bathroom sink drains really slow',
  },
  {
    slug: 'garbage-disposal-hums',
    trade: 'plumbing',
    h1: 'Garbage disposal hums but will not spin: how to unjam it',
    title: 'Garbage Disposal Hums but Won\'t Spin: Unjam It First',
    description: 'A humming disposal is usually jammed, not dead. Turn off the power, free it with a disposal wrench, press reset, and only then think about a new unit.',
    lede: 'When a disposal hums, the motor is getting power but the grinding plate is stuck. Freeing the jam fixes most of them for the price of a wrench.',
    before: 'Turn the disposal off at the switch, and unplug it or switch off its breaker before touching it. Never put your hand inside a disposal.',
    checks: [
      ['The jam', 'Fit a disposal wrench, which is a 1/4 inch hex key, into the socket on the bottom center of the unit. Work it back and forth until it turns a full circle freely.'],
      ['Something stuck inside', 'With the power still off, look in with a flashlight and pull out anything lodged in the chamber with tongs or pliers.'],
      ['The reset button', 'Press the red reset button on the bottom of the unit, restore power, and test it with cold water running.'],
      ['The breaker', 'If there is no sound at all after a reset, check the breaker.'],
      ['The unit itself', 'If it still only hums after spinning freely by hand, or water leaks from the body of the unit, it needs replacing.'],
    ],
    parts: [
      ['Disposal wrench', 'A 1/4 inch hex key. Many units came with one, and a standard hex key the same size works.'],
      ['Replacement disposal', 'Only if it leaks from the body or still will not run. The same brand often fits the existing mount.'],
      ['Disposal splash guard', 'Optional, if the rubber guard is torn.'],
    ],
    tools: ['1/4 inch hex key or disposal wrench', 'Flashlight', 'Tongs or long pliers'],
    callPro: [
      'The unit is hardwired and replacing it means disconnecting wiring',
      'It trips the breaker again and again',
      'The sink drain itself is clogged below the disposal',
    ],
    appJob: 'Garbage disposal just hums and doesn\'t spin',
  },
  {
    slug: 'water-dripping-from-indoor-ac-unit',
    trade: 'hvac',
    h1: 'Water dripping from the indoor AC unit: what to check',
    title: 'Water Dripping From Indoor AC Unit: What to Check',
    description: 'Water leaking from your indoor AC unit or air handler is usually a clogged condensate drain line. Check these in order and get the parts to clear it.',
    lede: 'Your air conditioner pulls moisture out of the air and drains it away through a small pipe. When that path clogs, the water ends up on the floor.',
    before: 'Turn the system off at the thermostat, and switch off the unit\'s power before opening any panel.',
    checks: [
      ['The air filter', 'A clogged filter can make the coil freeze. When the ice melts, it overwhelms the drain pan. Replace the filter if it is dirty.'],
      ['The condensate drain line', 'Find the PVC drain pipe near the indoor unit. Many have a capped access port: flush it with a cup of white vinegar or water, or pull the clog out from the outside end with a wet/dry vacuum. Avoid bleach, which can damage some pans and pumps.'],
      ['The drain pan', 'Look for standing water, rust or cracks in the pan under the coil.'],
      ['The condensate pump', 'If your unit has a small pump box, make sure it is plugged in and its float is not stuck. A pump that runs but moves no water needs replacing.'],
      ['Ice on the coil', 'If you see ice on the coil or the refrigerant lines, turn cooling off and run the fan to thaw it, then see the guide to ice on the AC line.'],
    ],
    parts: [
      ['HVAC air filter', 'The size is printed on the frame of the old filter.'],
      ['Condensate drain line tablets or cleaner', 'Helps keep the line from clogging again.'],
      ['PVC drain line fittings', 'Condensate lines are usually 3/4 inch. Only if a fitting is cracked.'],
      ['Condensate pump', 'Only if yours has failed. Match the voltage and outlet size.'],
    ],
    tools: ['Wet/dry vacuum', 'Flashlight', 'Towels'],
    callPro: [
      'The drain pan is cracked or rusted through',
      'The coil keeps freezing after you replace the filter',
      'Water is reaching electrical parts or a furnace below the unit',
    ],
    appJob: 'Water dripping from the indoor AC unit',
  },
  {
    slug: 'ice-on-ac-line',
    trade: 'hvac',
    h1: 'Ice on the AC line or coil: causes and what to check',
    title: 'Ice on Your AC Line: Causes and What to Check',
    description: 'Ice on the pipe going into your AC is usually an airflow problem, like a dirty filter or blocked vents, not refrigerant. Check these before calling for service.',
    lede: 'Ice forms when the indoor coil gets too cold, and the most common reason is that not enough warm air is moving across it.',
    before: 'Turn cooling off at the thermostat and set the fan to on so the ice melts. Running the AC while it is frozen can damage the compressor. Put towels down for the meltwater.',
    checks: [
      ['The air filter', 'A clogged filter is the most common cause. Replace it.'],
      ['Vents and return grilles', 'Open any closed vents, and move furniture and rugs off the return grilles.'],
      ['Airflow at the vents', 'With the fan on, you should feel steady airflow. Weak airflow with a clean filter can mean a dirty blower or a failing blower motor.'],
      ['The weather', 'Running the AC on a cool night, roughly below 60°F outside, can freeze the coil.'],
      ['Refrigerant', 'If airflow is good and the coil freezes again, the system may be low on refrigerant from a leak. That needs a licensed HVAC technician, not a store-bought kit.'],
    ],
    parts: [
      ['HVAC air filter', 'The size is printed on the frame of the old filter. Replace return grille filters too, if you have them.'],
      ['Foam AC coil cleaner', 'Only if you can reach a visibly dirty coil through an access panel, with the power off.'],
    ],
    tools: ['Flashlight', 'Towels or a wet/dry vacuum for the meltwater'],
    callPro: [
      'It freezes again after a new filter and open vents',
      'The outdoor unit buzzes, or its fan is not spinning',
      'You hear hissing or see oily residue at the refrigerant lines',
    ],
    appJob: 'There\'s ice on the pipe going into my AC',
  },
  {
    slug: 'hole-in-drywall',
    trade: 'carpentry',
    h1: 'How to patch a hole in drywall: parts by hole size',
    title: 'Patch a Hole in Drywall: Parts List by Hole Size',
    description: 'The patch you buy depends on the size of the hole. Parts lists for nail holes, doorknob-size holes and larger damage, plus the tools to finish it smooth.',
    lede: 'Measure the hole first. Small, medium and large holes each take a different patch.',
    before: 'Before cutting a hole any bigger, shine a flashlight inside to check for wires and pipes, and keep your cuts shallow.',
    checks: [
      ['Under 1/2 inch: nail and screw holes', 'Fill with lightweight spackle, let it dry, sand it flat and paint.'],
      ['Up to about 4 inches: doorknob holes', 'Cover with a self-adhesive mesh patch, then feather two or three thin coats of joint compound over it, sanding between coats.'],
      ['Over 4 inches', 'Cut the damage into a clean square, screw a wood or drywall backer strip inside the opening, screw in a new piece of drywall cut to fit, then tape and finish the seams.'],
      ['Is the wall damp?', 'If the drywall is soft, stained or crumbling, find and fix the water source before patching.'],
    ],
    parts: [
      ['Lightweight spackling compound', 'For small holes.'],
      ['Self-adhesive drywall repair patch', 'Pick a size an inch or two bigger than the hole.'],
      ['Drywall panel or scrap', 'For large holes. Walls are usually 1/2 inch thick; measure yours at the hole.'],
      ['Coarse-thread drywall screws, 1-1/4 inch', 'To fasten the new piece and backer strips.'],
      ['Joint compound and mesh tape', 'For finishing the seams.'],
      ['Primer and matching paint', 'Raw compound soaks up paint unevenly without primer.'],
    ],
    tools: ['Putty knives, 4 and 6 inch', 'Drywall saw', 'Utility knife', 'Sanding sponge', 'Drill/driver'],
    callPro: [
      'The damage came from a leak, or there is mold',
      'Wires or pipes behind the hole are damaged',
      'A large hole in a ceiling',
    ],
    appJob: 'My kid put a hole in the drywall',
  },
  {
    slug: 'door-wont-latch',
    trade: 'carpentry',
    h1: 'Door will not latch: what to check before buying hardware',
    title: 'Door Won\'t Latch? What to Check and Parts to Buy',
    description: 'A door that will not latch usually has loose hinges or a strike plate out of line. Check these in order before you replace the door hardware.',
    lede: 'Close the door slowly and watch where the latch meets the strike plate. Most fixes are adjustments that cost little or nothing.',
    before: null,
    checks: [
      ['Loose hinge screws', 'Tighten every hinge screw. If one spins in place, replace a screw in the top hinge with a 3 inch screw that reaches the wall framing.'],
      ['Strike plate alignment', 'Rub a little chalk or lipstick on the latch and close the door. If the mark lands above or below the opening in the strike plate, file the opening larger or move the plate.'],
      ['The latch does not reach', 'If the gap between the door and the frame is too wide, shim behind the strike plate or fit an adjustable strike.'],
      ['A sticking latch', 'If the latch bolt does not spring all the way out, spray it with dry lubricant, or replace the latch.'],
      ['A swollen or shifted door', 'If the door rubs the frame, humidity or settling has moved it. Tighten the hinges first, then plane the edge if it still rubs.'],
    ],
    parts: [
      ['3 inch hinge screws', 'Match the finish of your hinges.'],
      ['Adjustable or replacement strike plate', 'Match the finish and the shape of the corners.'],
      ['Door latch', 'Measure the backset, the distance from the door edge to the center of the knob hole: usually 2-3/8 or 2-3/4 inch.'],
      ['Dry graphite or silicone lubricant', 'Oil-based sprays attract dust inside the latch.'],
      ['Wood glue and toothpicks or wood filler', 'To rebuild stripped screw holes.'],
    ],
    tools: ['Screwdriver or drill', 'Metal file', 'Chisel', 'Tape measure'],
    callPro: [
      'The door frame is cracked or pulling away from the wall',
      'Doors all over the house start sticking at once, which can mean the house is settling',
      'An exterior door that will not lock securely',
    ],
    appJob: 'Bedroom door won\'t latch anymore',
  },
  {
    slug: 'windshield-wipers-smear',
    trade: 'auto',
    h1: 'Windshield wipers smear: what to check and what to buy',
    title: 'Windshield Wipers Smear? What to Check and Buy',
    description: 'Smearing wipers usually mean worn blades or dirty glass. How to check, how to find your blade sizes, and what else to pick up at the parts store.',
    lede: 'Wiper rubber wears out from sun and heat, often within a year. Rule out dirty glass first, because it costs nothing.',
    before: null,
    checks: [
      ['Dirty glass and blades', 'Clean the windshield with glass cleaner and wipe the rubber edge of each blade with a damp cloth. If the smearing stops, you are done.'],
      ['Worn rubber', 'Cracked, stiff, torn or rounded rubber edges mean new blades.'],
      ['Blade sizes', 'The driver and passenger blades are often different lengths. Your owner\'s manual lists them, or the parts store can look them up by year, make and model.'],
      ['Washer fluid', 'Plain water or an empty reservoir makes smearing worse. Fill it with washer fluid.'],
      ['Wiper arm pressure', 'If new blades still skip or chatter on one side, the arm may be bent or its spring weak.'],
    ],
    parts: [
      ['Wiper blades, driver and passenger', 'Sizes by vehicle. Replace both at once.'],
      ['Rear wiper blade', 'If your car has one.'],
      ['Windshield washer fluid', 'A de-icer blend if you get freezing weather.'],
    ],
    tools: ['None for most blades. A small flat screwdriver helps with some clips.'],
    callPro: [
      'The wipers do not move, or move slowly, which points to the motor or linkage',
      'The wipers stop in the middle of the windshield',
    ],
    appJob: 'Wipers smear instead of clearing the glass',
  },
  {
    slug: 'headlight-out',
    trade: 'auto',
    h1: 'Headlight out: bulb, fuse and what to check first',
    title: 'Headlight Out? Bulb, Fuse and What to Check First',
    description: 'When one headlight is out it is usually the bulb. How to confirm it, find the right bulb number for your car, and what to check if a new bulb does not work.',
    lede: 'If only one headlight is out, the bulb has most likely burned out. If both went out at the same time, look at the fuses first.',
    before: 'Turn the lights off and let the bulb cool. Do not touch the glass of a halogen bulb with bare fingers, because skin oil shortens its life.',
    checks: [
      ['Low beam or high beam', 'Switch to high beams. Many cars use separate bulbs for each, so note which one is out.'],
      ['The bulb', 'Remove the bulb from the back of the headlight housing. A broken filament or darkened glass confirms it.'],
      ['The bulb number', 'Your owner\'s manual lists it, for example H11 or 9005, or the parts store can look it up by year, make and model.'],
      ['Fuses', 'If both sides are out, or a new bulb does not light, check the headlight fuses. The fuse box cover shows which ones they are.'],
      ['The connector', 'A melted or corroded plug behind the bulb can also cut power. It can be replaced with a new connector pigtail.'],
    ],
    parts: [
      ['Headlight bulbs, as a pair', 'Replacing both sides keeps brightness and color matched.'],
      ['Headlight fuse', 'Match the amperage printed on the old fuse or the fuse box cover.'],
      ['Dielectric grease', 'A small amount on the connector keeps out moisture.'],
      ['Headlight connector pigtail', 'Only if the plug is melted or corroded.'],
    ],
    tools: ['Gloves or a clean cloth', 'Screwdriver or trim tool, on some cars', 'Flashlight'],
    callPro: [
      'LED or HID headlights, which usually are not simple bulb swaps, and HID systems carry high voltage',
      'The bulb can only be reached by removing the bumper or headlight assembly',
      'New bulbs keep burning out quickly',
    ],
    appJob: 'Left headlight is out',
  },
  {
    slug: 'washer-wont-drain',
    trade: 'appliance',
    h1: 'Washer will not drain: what to check and what to buy',
    title: 'Washer Won\'t Drain: What to Check and Parts to Buy',
    description: 'Washer fills but will not drain? Check the drain hose, the pump filter and the lid switch in this order before buying a new drain pump.',
    lede: 'Most washers that will not drain have something blocking the water on its way out: a kinked hose, a sock in the pump filter, or a clog in the house drain.',
    before: 'Unplug the washer first. Have towels and a shallow pan ready, because there will be water in the drum and the hose.',
    checks: [
      ['The drain hose', 'Pull the washer out and make sure the hose is not kinked or crushed. Disconnect it and check it for a clog.'],
      ['The pump filter', 'Many front-load washers have a filter behind a small panel at the bottom front. Drain it slowly into a pan and clear out lint, coins and socks.'],
      ['The house drain', 'If water backs up out of the standpipe or laundry sink when the washer drains, the clog is in the house drain, not the washer.'],
      ['The lid switch or door lock', 'Most washers will not drain or spin if they think the lid or door is open. A broken lid switch or door lock stops the cycle.'],
      ['The drain pump', 'If the pump hums but no water moves after the filter is clear, or it makes no sound at all, the pump may need replacing.'],
    ],
    parts: [
      ['Washer drain hose', 'Match the length and the fitting at each end.'],
      ['Hose clamp', 'If the old one is rusted or loose.'],
      ['Washer drain pump', 'Order by the model number on the tag inside the lid or door frame.'],
      ['Lid switch or door lock', 'Also by model number.'],
    ],
    tools: ['Towels and a shallow pan', 'Pliers', 'Flat screwdriver', 'Bucket'],
    callPro: [
      'Water leaks from under the washer while it runs',
      'Error codes remain after the filter and hose are clear',
      'The house drain is backing up, which is a job for a plumber',
    ],
    appJob: 'Washer fills but won\'t drain',
  },
  {
    slug: 'dryer-takes-too-long',
    trade: 'appliance',
    h1: 'Dryer takes too long to dry: check the vent first',
    title: 'Dryer Takes Too Long to Dry? Check the Vent First',
    description: 'A dryer that runs forever with damp clothes usually has a clogged lint screen or vent, which is also a fire risk. Check these in order and get the vent parts.',
    lede: 'A dryer has to push hot, wet air outside. When lint blocks that path, drying slows down and heat builds up where it should not.',
    before: 'Lint buildup is a fire hazard. If the dryer or laundry room smells hot, stop using it until the vent is cleared. Unplug the dryer before moving it, and on a gas dryer do not pull on the gas line. If you smell gas, leave and call your gas utility from outside.',
    checks: [
      ['The lint screen', 'Clean it every load. If water beads on it, dryer sheets have left a film; wash it with soap and water.'],
      ['The outside vent hood', 'With the dryer running, feel the air at the vent outside. Weak airflow means a blockage. Clear lint from the flap.'],
      ['The vent duct', 'Disconnect the duct behind the dryer and clean it with a vent brush kit. Replace crushed or plastic foil duct with semi-rigid or rigid metal duct.'],
      ['Load size and settings', 'Overloaded drums and the wrong cycle setting can double drying time.'],
      ['Heat', 'If the air never gets warm with a clear vent, an electric dryer may have a failed heating element or thermal fuse. A gas dryer that will not heat needs a technician.'],
    ],
    parts: [
      ['Dryer vent cleaning brush kit', 'Long flexible rods that reach through the duct.'],
      ['4 inch semi-rigid or rigid metal dryer duct', 'Keep the run as short and straight as you can.'],
      ['4 inch clamps and foil tape', 'Use foil tape, not cloth duct tape, and no screws, which catch lint.'],
      ['Exterior dryer vent hood', 'If the flap is broken or stuck.'],
      ['Dryer thermal fuse', 'Electric dryers only. Order by model number.'],
    ],
    tools: ['Screwdriver or nut driver', 'Vacuum', 'Vent brush kit'],
    callPro: [
      'A gas dryer that will not heat, or any smell of gas',
      'The vent runs through the roof, or a long way inside a wall',
      'The dryer scorches clothes or shuts off hot',
    ],
    appJob: 'Dryer runs forever and clothes stay damp',
  },
];

module.exports = { TRADES, JOBS, UPDATED: '2026-09-16' };
